"""add m3 settings

Revision ID: c45a71864b94
Revises: 69b4468d9fe0
Create Date: 2026-06-10 12:48:23.590788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45a71864b94'
down_revision: Union[str, None] = '69b4468d9fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_settings', sa.Column('business_rules', sa.String(), nullable=True))
    op.add_column('bot_settings', sa.Column('marketing_rules', sa.String(), nullable=True))
    op.add_column('bot_settings', sa.Column('escalation_policy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_settings', 'escalation_policy')
    op.drop_column('bot_settings', 'marketing_rules')
    op.drop_column('bot_settings', 'business_rules')
    # ### end Alembic commands ###
